package nl.d2n.model;

public enum UpdateAction {
    READ_MAP,
    ADD_BLUEPRINT,
    DEPLETE_BUILDING,
    DEPLETE_ZONE,
    LOCK_BUILDING,
    REMOVE_BLUEPRINT,
    REPLENISH_BUILDING,
    REPLENISH_ZONE,
    SAVE_CAMPING,
    SAVE_ITEMS,
    SAVE_PEEK,
    SAVE_ZOMBIES,
    SAVE_SCOUT_SENSE,
    UNLOCK_BUILDING,
    UNVISIT_ZONE,
    VISIT_ZONE,
    UPDATE_ZONE,
    UPDATE_ZONE_EXTENDED
}
