curl http://data.die2nite.com/gfx/icons/item_bgrenade.gif > item_bgrenade.gif
curl http://data.die2nite.com/gfx/icons/item_courroie.gif > item_courroie.gif
curl http://data.die2nite.com/gfx/icons/item_digger.gif > item_digger.gif
curl http://data.die2nite.com/gfx/icons/item_electro.gif > item_electro.gif
curl http://data.die2nite.com/gfx/icons/item_firework_tube.gif > item_firework_tube.gif
curl http://data.die2nite.com/gfx/icons/item_hmeat.gif > item_hmeat.gif
curl http://data.die2nite.com/gfx/icons/item_jerrycan.gif > item_jerrycan.gif
curl http://data.die2nite.com/gfx/icons/item_mace_parts.gif > item_mace_parts.gif
curl http://data.die2nite.com/gfx/icons/item_meat.gif > item_meat.gif
curl http://data.die2nite.com/gfx/icons/item_plate.gif > item_plate.gif
curl http://data.die2nite.com/gfx/icons/item_rp_book2.gif > item_rp_book2.gif
curl http://data.die2nite.com/gfx/icons/item_tagger.gif > item_tagger.gif
curl http://data.die2nite.com/gfx/icons/item_tube.gif > item_tube.gif
curl http://data.die2nite.com/gfx/icons/item_vegetable_tasty.gif > item_vegetable_tasty.gif
curl http://data.die2nite.com/gfx/icons/item_wood_beam.gif > item_wood_beam.gif
curl http://data.die2nite.com/gfx/icons/item_wood_plate.gif > item_wood_plate.gif
curl http://data.die2nite.com/gfx/icons/r_dhang.gif > r_dhang.gif
curl http://data.die2nite.com/gfx/icons/small_arma.gif > small_arma.gif
curl http://data.die2nite.com/gfx/icons/small_bamba.gif > small_bamba.gif
curl http://data.die2nite.com/gfx/icons/small_barbed.gif > small_barbed.gif
curl http://data.die2nite.com/gfx/icons/small_building.gif > small_building.gif
curl http://data.die2nite.com/gfx/icons/small_cafet.gif > small_cafet.gif
curl http://data.die2nite.com/gfx/icons/small_canon.gif > small_canon.gif
curl http://data.die2nite.com/gfx/icons/small_cemetery.gif > small_cemetery.gif
curl http://data.die2nite.com/gfx/icons/small_chicken.gif > small_chicken.gif
curl http://data.die2nite.com/gfx/icons/small_city_up.gif > small_city_up.gif
curl http://data.die2nite.com/gfx/icons/small_derrick.gif > small_derrick.gif
curl http://data.die2nite.com/gfx/icons/small_dig.gif > small_dig.gif
curl http://data.die2nite.com/gfx/icons/small_door_closed.gif > small_door_closed.gif
curl http://data.die2nite.com/gfx/icons/small_eden.gif > small_eden.gif
curl http://data.die2nite.com/gfx/icons/small_factory.gif > small_factory.gif
curl http://data.die2nite.com/gfx/icons/small_fence.gif > small_fence.gif
curl http://data.die2nite.com/gfx/icons/small_fleshcage.gif > small_fleshcage.gif
curl http://data.die2nite.com/gfx/icons/small_gather.gif > small_gather.gif
curl http://data.die2nite.com/gfx/icons/small_grater.gif > small_grater.gif
curl http://data.die2nite.com/gfx/icons/small_grinder.gif > small_grinder.gif
curl http://data.die2nite.com/gfx/icons/small_howlingbait.gif > small_howlingbait.gif
curl http://data.die2nite.com/gfx/icons/small_labyrinth.gif > small_labyrinth.gif
curl http://data.die2nite.com/gfx/icons/small_lastchance.gif > small_lastchance.gif
curl http://data.die2nite.com/gfx/icons/small_lighthouse.gif > small_lighthouse.gif
curl http://data.die2nite.com/gfx/icons/small_meatbarbed.gif > small_meatbarbed.gif
curl http://data.die2nite.com/gfx/icons/small_pmvbig.gif > small_pmvbig.gif
curl http://data.die2nite.com/gfx/icons/small_redemption.gif > small_redemption.gif
curl http://data.die2nite.com/gfx/icons/small_refine.gif > small_refine.gif
curl http://data.die2nite.com/gfx/icons/small_rocketperf.gif > small_rocketperf.gif
curl http://data.die2nite.com/gfx/icons/small_saw.gif > small_saw.gif
curl http://data.die2nite.com/gfx/icons/small_scarecrow.gif > small_scarecrow.gif
curl http://data.die2nite.com/gfx/icons/small_score.gif > small_score.gif
curl http://data.die2nite.com/gfx/icons/small_shower.gif > small_shower.gif
curl http://data.die2nite.com/gfx/icons/small_slaughterhouse.gif > small_slaughterhouse.gif
curl http://data.die2nite.com/gfx/icons/small_slave.gif > small_slave.gif
curl http://data.die2nite.com/gfx/icons/small_spears.gif > small_spears.gif
curl http://data.die2nite.com/gfx/icons/small_sprinkler.gif > small_sprinkler.gif
curl http://data.die2nite.com/gfx/icons/small_strategy.gif > small_strategy.gif
curl http://data.die2nite.com/gfx/icons/small_tnt.gif > small_tnt.gif
curl http://data.die2nite.com/gfx/icons/small_trap.gif > small_trap.gif
curl http://data.die2nite.com/gfx/icons/small_trash.gif > small_trash.gif
curl http://data.die2nite.com/gfx/icons/small_trashclean.gif > small_trashclean.gif
curl http://data.die2nite.com/gfx/icons/small_valve.gif > small_valve.gif
curl http://data.die2nite.com/gfx/icons/small_ventilation.gif > small_ventilation.gif
curl http://data.die2nite.com/gfx/icons/small_wallimprove.gif > small_wallimprove.gif
curl http://data.die2nite.com/gfx/icons/small_watchmen.gif > small_watchmen.gif
curl http://data.die2nite.com/gfx/icons/small_water.gif > small_water.gif
curl http://data.die2nite.com/gfx/icons/small_watercanon.gif > small_watercanon.gif
curl http://data.die2nite.com/gfx/icons/small_waterdetect.gif > small_waterdetect.gif
curl http://data.die2nite.com/gfx/icons/small_waterhole.gif > small_waterhole.gif
curl http://data.die2nite.com/gfx/icons/small_waterspray.gif > small_waterspray.gif
curl http://data.die2nite.com/gfx/icons/status_terror.gif > status_terror.gif
curl http://data.die2nite.com/gfx/icons/item_meca_parts.gif > item_meca_parts.gif
curl http://data.die2nite.com/gfx/icons/item_bgrenade.gif > item_bgrenade.gif
curl http://data.die2nite.com/gfx/icons/item_shield.gif > item_shield.gif
curl http://data.die2nite.com/gfx/icons/small_strategy.gif > small_strategy.gif
curl http://data.die2nite.com/gfx/icons/small_trash.gif > small_trash.gif
curl http://data.die2nite.com/gfx/icons/small_court.gif > small_court.gif
curl http://data.die2nite.com/gfx/icons/small_wheel.gif > small_wheel.gif
curl http://data.die2nite.com/gfx/icons/small_castle.gif > small_castle.gif
curl http://data.die2nite.com/gfx/icons/small_appletree.gif > small_appletree.gif
curl http://data.die2nite.com/gfx/icons/item_plate.gif > item_plate.gif
curl http://data.die2nite.com/gfx/icons/small_acidspray.gif > small_acidspray.gif
