curl http://data.die2nite.com/gfx/icons/r_rp.gif > distinctions/r_rp.gif 
curl http://data.die2nite.com/gfx/icons/r_ban.gif > distinctions/r_ban.gif 
curl http://data.die2nite.com/gfx/icons/r_drug.gif > distinctions/r_drug.gif 
curl http://data.die2nite.com/gfx/icons/r_bgum.gif > distinctions/r_bgum.gif 
curl http://data.die2nite.com/gfx/icons/r_deco.gif > distinctions/r_deco.gif 
curl http://data.die2nite.com/gfx/icons/r_maso.gif > distinctions/r_maso.gif 
curl http://data.die2nite.com/gfx/icons/r_camp.gif > distinctions/r_camp.gif 
curl http://data.die2nite.com/gfx/icons/r_cgarb.gif > distinctions/r_cgarb.gif 
curl http://data.die2nite.com/gfx/icons/r_wound.gif > distinctions/r_wound.gif 
curl http://data.die2nite.com/gfx/icons/r_share.gif > distinctions/r_share.gif 
curl http://data.die2nite.com/gfx/icons/r_forum.gif > distinctions/r_forum.gif 
curl http://data.die2nite.com/gfx/icons/r_cookr.gif > distinctions/r_cookr.gif 
curl http://data.die2nite.com/gfx/icons/r_theft.gif > distinctions/r_theft.gif 
curl http://data.die2nite.com/gfx/icons/r_dcity.gif > distinctions/r_dcity.gif 
curl http://data.die2nite.com/gfx/icons/r_killz.gif > distinctions/r_killz.gif 
curl http://data.die2nite.com/gfx/icons/r_cannib.gif > distinctions/r_cannib.gif 
curl http://data.die2nite.com/gfx/icons/r_heroac.gif > distinctions/r_heroac.gif 
curl http://data.die2nite.com/gfx/icons/r_cooked.gif > distinctions/r_cooked.gif 
curl http://data.die2nite.com/gfx/icons/r_hbuild.gif > distinctions/r_hbuild.gif 
curl http://data.die2nite.com/gfx/icons/r_jguard.gif > distinctions/r_jguard.gif 
curl http://data.die2nite.com/gfx/icons/r_doutsd.gif > distinctions/r_doutsd.gif 
curl http://data.die2nite.com/gfx/icons/r_jcolle.gif > distinctions/r_jcolle.gif 
curl http://data.die2nite.com/gfx/icons/r_refine.gif > distinctions/r_refine.gif 
curl http://data.die2nite.com/gfx/icons/r_cobaye.gif > distinctions/r_cobaye.gif 
curl http://data.die2nite.com/gfx/icons/r_nodrug.gif > distinctions/r_nodrug.gif 
curl http://data.die2nite.com/gfx/icons/r_animal.gif > distinctions/r_animal.gif 
curl http://data.die2nite.com/gfx/icons/r_alcool.gif > distinctions/r_alcool.gif 
curl http://data.die2nite.com/gfx/icons/r_wrestl.gif > distinctions/r_wrestl.gif 
curl http://data.die2nite.com/gfx/icons/r_chstxl.gif > distinctions/r_chstxl.gif 
curl http://data.die2nite.com/gfx/icons/r_solban.gif > distinctions/r_solban.gif 
curl http://data.die2nite.com/gfx/icons/r_broken.gif > distinctions/r_broken.gif 
curl http://data.die2nite.com/gfx/icons/r_watgun.gif > distinctions/r_watgun.gif 
curl http://data.die2nite.com/gfx/icons/r_surgrp.gif > distinctions/r_surgrp.gif 
curl http://data.die2nite.com/gfx/icons/r_homeup.gif > distinctions/r_homeup.gif 
curl http://data.die2nite.com/gfx/icons/r_buildr.gif > distinctions/r_buildr.gif 
curl http://data.die2nite.com/gfx/icons/r_plundr.gif > distinctions/r_plundr.gif 
curl http://data.die2nite.com/gfx/icons/r_rrefer.gif > distinctions/r_rrefer.gif 
curl http://data.die2nite.com/gfx/icons/r_digger.gif > distinctions/r_digger.gif 
curl http://data.die2nite.com/gfx/icons/r_cwater.gif > distinctions/r_cwater.gif 
curl http://data.die2nite.com/gfx/icons/r_jrangr.gif > distinctions/r_jrangr.gif 
curl http://data.die2nite.com/gfx/icons/r_repair.gif > distinctions/r_repair.gif 
curl http://data.die2nite.com/gfx/icons/r_explor.gif > distinctions/r_explor.gif 
curl http://data.die2nite.com/gfx/icons/r_wondrs.gif > distinctions/r_wondrs.gif 
curl http://data.die2nite.com/gfx/icons/r_cmplst.gif > distinctions/r_cmplst.gif 
curl http://data.die2nite.com/gfx/icons/r_surlst.gif > distinctions/r_surlst.gif 
curl http://data.die2nite.com/gfx/icons/r_beta.gif > distinctions/r_beta.gif 
curl http://data.die2nite.com/gfx/icons/r_sandb.gif > distinctions/r_sandb.gif 
curl http://data.die2nite.com/gfx/icons/r_ddrug.gif > distinctions/r_ddrug.gif 
curl http://data.die2nite.com/gfx/icons/r_dinfec.gif > distinctions/r_dinfec.gif 
curl http://data.die2nite.com/gfx/icons/r_batgun.gif > distinctions/r_batgun.gif 
curl http://data.die2nite.com/gfx/icons/r_jtamer.gif > distinctions/r_jtamer.gif 
curl http://data.die2nite.com/gfx/icons/r_dwater.gif > distinctions/r_dwater.gif 
curl http://data.die2nite.com/gfx/icons/r_drgmkr.gif > distinctions/r_drgmkr.gif 
curl http://data.die2nite.com/gfx/icons/r_winbas.gif > distinctions/r_winbas.gif 
curl http://data.die2nite.com/gfx/icons/r_tronco.gif > distinctions/r_tronco.gif 
curl http://data.die2nite.com/gfx/icons/r_wintop.gif > distinctions/r_wintop.gif 
curl http://data.die2nite.com/gfx/icons/r_explo2.gif > distinctions/r_explo2.gif 
curl http://data.die2nite.com/gfx/icons/r_ebuild.gif > distinctions/r_ebuild.gif 
curl http://data.die2nite.com/gfx/icons/r_ebgros.gif > distinctions/r_ebgros.gif 
curl http://data.die2nite.com/gfx/icons/r_brep.gif > distinctions/r_brep.gif 
curl http://data.die2nite.com/gfx/icons/r_ebpmv.gif > distinctions/r_ebpmv.gif 
curl http://data.die2nite.com/gfx/icons/r_ebcstl.gif > distinctions/r_ebcstl.gif 
curl http://data.die2nite.com/gfx/icons/r_cott.gif > distinctions/r_cott.gif
curl http://data.die2nite.com/gfx/icons/r_ermwin.gif > distinctions/r_ermwin.gif
curl http://data.die2nite.com/gfx/icons/r_lepre.gif > distinctions/r_lepre.gif
curl http://data.die2nite.com/gfx/icons/r_ptame.gif > distinctions/r_ptame.gif
curl http://data.die2nite.com/gfx/icons/r_armag.gif > distinctions/r_armag.gif
curl http://data.die2nite.com/gfx/icons/r_guide.gif > distinctions/r_guide.gif
curl http://data.die2nite.com/gfx/icons/r_jsham.gif > distinctions/r_jsham.gif
curl http://data.die2nite.com/gfx/icons/r_mystic.gif > distinctions/r_mystic.gif
curl http://data.die2nite.com/gfx/icons/r_collec.gif > distinctions/r_collec.gif
