curl http://data.die2nite.com/gfx/icons/item_bag.gif > items/bag.gif
curl http://data.die2nite.com/gfx/icons/item_bagxl.gif > items/bagxl.gif
curl http://data.die2nite.com/gfx/icons/item_bandage.gif > items/bandage.gif
curl http://data.die2nite.com/gfx/icons/item_banned_note.gif > items/banned_note.gif
curl http://data.die2nite.com/gfx/icons/item_bed.gif > items/bed.gif
curl http://data.die2nite.com/gfx/icons/item_beta_drug_bad.gif > items/beta_drug_bad.gif
curl http://data.die2nite.com/gfx/icons/item_bgrenade.gif > items/bgrenade.gif
curl http://data.die2nite.com/gfx/icons/item_bgrenade_empty.gif > items/bgrenade_empty.gif
curl http://data.die2nite.com/gfx/icons/item_big_pgun.gif > items/big_pgun.gif
curl http://data.die2nite.com/gfx/icons/item_big_pgun_empty.gif > items/big_pgun_empty.gif
curl http://data.die2nite.com/gfx/icons/item_big_pgun_part.gif > items/big_pgun_part.gif
curl http://data.die2nite.com/gfx/icons/item_bone.gif > items/bone.gif
curl http://data.die2nite.com/gfx/icons/item_bone_meat.gif > items/bone_meat.gif
curl http://data.die2nite.com/gfx/icons/item_book_gen_box.gif > items/book_gen_box.gif
curl http://data.die2nite.com/gfx/icons/item_book_gen_letter.gif > items/book_gen_letter.gif
curl http://data.die2nite.com/gfx/icons/item_boomfruit.gif > items/boomfruit.gif
curl http://data.die2nite.com/gfx/icons/item_bplan_box.gif > items/bplan_box.gif
curl http://data.die2nite.com/gfx/icons/item_bplan_box_e.gif > items/bplan_box_e.gif
curl http://data.die2nite.com/gfx/icons/item_bplan_c.gif > items/bplan_c.gif
curl http://data.die2nite.com/gfx/icons/item_bplan_drop.gif > items/bplan_drop.gif
curl http://data.die2nite.com/gfx/icons/item_bplan_e.gif > items/bplan_e.gif
curl http://data.die2nite.com/gfx/icons/item_bplan_r.gif > items/bplan_r.gif
curl http://data.die2nite.com/gfx/icons/item_bplan_u.gif > items/bplan_u.gif
curl http://data.die2nite.com/gfx/icons/item_can.gif > items/can.gif
curl http://data.die2nite.com/gfx/icons/item_can_open.gif > items/can_open.gif
curl http://data.die2nite.com/gfx/icons/item_can_opener.gif > items/can_opener.gif
curl http://data.die2nite.com/gfx/icons/item_cards.gif > items/cards.gif
curl http://data.die2nite.com/gfx/icons/item_carpet.gif > items/carpet.gif
curl http://data.die2nite.com/gfx/icons/item_cart.gif > items/cart.gif
curl http://data.die2nite.com/gfx/icons/item_cart_part.gif > items/cart_part.gif
curl http://data.die2nite.com/gfx/icons/item_car_door.gif > items/car_door.gif
curl http://data.die2nite.com/gfx/icons/item_car_door_part.gif > items/car_door_part.gif
curl http://data.die2nite.com/gfx/icons/item_chain.gif > items/chain.gif
curl http://data.die2nite.com/gfx/icons/item_chainsaw.gif > items/chainsaw.gif
curl http://data.die2nite.com/gfx/icons/item_chainsaw_empty.gif > items/chainsaw_empty.gif
curl http://data.die2nite.com/gfx/icons/item_chainsaw_part.gif > items/chainsaw_part.gif
curl http://data.die2nite.com/gfx/icons/item_chair.gif > items/chair.gif
curl http://data.die2nite.com/gfx/icons/item_chair_basic.gif > items/chair_basic.gif
curl http://data.die2nite.com/gfx/icons/item_chama.gif > items/chama.gif
curl http://data.die2nite.com/gfx/icons/item_chama_tasty.gif > items/chama_tasty.gif
curl http://data.die2nite.com/gfx/icons/item_chest.gif > items/chest.gif
curl http://data.die2nite.com/gfx/icons/item_chest_citizen.gif > items/chest_citizen.gif
curl http://data.die2nite.com/gfx/icons/item_chest_food.gif > items/chest_food.gif
curl http://data.die2nite.com/gfx/icons/item_chest_hero.gif > items/chest_hero.gif
curl http://data.die2nite.com/gfx/icons/item_chest_tools.gif > items/chest_tools.gif
curl http://data.die2nite.com/gfx/icons/item_chest_xl.gif > items/chest_xl.gif
curl http://data.die2nite.com/gfx/icons/item_cigs.gif > items/cigs.gif
curl http://data.die2nite.com/gfx/icons/item_coffee.gif > items/coffee.gif
curl http://data.die2nite.com/gfx/icons/item_coffee_machine.gif > items/coffee_machine.gif
curl http://data.die2nite.com/gfx/icons/item_coffee_machine_part.gif > items/coffee_machine_part.gif
curl http://data.die2nite.com/gfx/icons/item_concrete.gif > items/concrete.gif
curl http://data.die2nite.com/gfx/icons/item_concrete_wall.gif > items/concrete_wall.gif
curl http://data.die2nite.com/gfx/icons/item_courroie.gif > items/courroie.gif
curl http://data.die2nite.com/gfx/icons/item_cutcut.gif > items/cutcut.gif
curl http://data.die2nite.com/gfx/icons/item_cutter.gif > items/cutter.gif
curl http://data.die2nite.com/gfx/icons/item_cyanure.gif > items/cyanure.gif
curl http://data.die2nite.com/gfx/icons/item_deco_box.gif > items/deco_box.gif
curl http://data.die2nite.com/gfx/icons/item_deto.gif > items/deto.gif
curl http://data.die2nite.com/gfx/icons/item_dice.gif > items/dice.gif
curl http://data.die2nite.com/gfx/icons/item_digger.gif > items/digger.gif
curl http://data.die2nite.com/gfx/icons/item_dish.gif > items/dish.gif
curl http://data.die2nite.com/gfx/icons/item_dish_tasty.gif > items/dish_tasty.gif
curl http://data.die2nite.com/gfx/icons/item_disinfect.gif > items/disinfect.gif
curl http://data.die2nite.com/gfx/icons/item_door.gif > items/door.gif
curl http://data.die2nite.com/gfx/icons/item_door_carpet.gif > items/door_carpet.gif
curl http://data.die2nite.com/gfx/icons/item_drug.gif > items/drug.gif
curl http://data.die2nite.com/gfx/icons/item_drug_hero.gif > items/drug_hero.gif
curl http://data.die2nite.com/gfx/icons/item_drug_random.gif > items/drug_random.gif
curl http://data.die2nite.com/gfx/icons/item_drug_water.gif > items/drug_water.gif
curl http://data.die2nite.com/gfx/icons/item_egg.gif > items/egg.gif
curl http://data.die2nite.com/gfx/icons/item_electro.gif > items/electro.gif
curl http://data.die2nite.com/gfx/icons/item_electro_box.gif > items/electro_box.gif
curl http://data.die2nite.com/gfx/icons/item_engine.gif > items/engine.gif
curl http://data.die2nite.com/gfx/icons/item_engine_part.gif > items/engine_part.gif
curl http://data.die2nite.com/gfx/icons/item_explo.gif > items/explo.gif
curl http://data.die2nite.com/gfx/icons/item_fence.gif > items/fence.gif
curl http://data.die2nite.com/gfx/icons/item_flash.gif > items/flash.gif
curl http://data.die2nite.com/gfx/icons/item_flesh.gif > items/flesh.gif
curl http://data.die2nite.com/gfx/icons/item_flesh_part.gif > items/flesh_part.gif
curl http://data.die2nite.com/gfx/icons/item_food_armag.gif > items/food_armag.gif
curl http://data.die2nite.com/gfx/icons/item_food_bag.gif > items/food_bag.gif
curl http://data.die2nite.com/gfx/icons/item_food_bar1.gif > items/food_bar1.gif
curl http://data.die2nite.com/gfx/icons/item_food_bar2.gif > items/food_bar2.gif
curl http://data.die2nite.com/gfx/icons/item_food_bar3.gif > items/food_bar3.gif
curl http://data.die2nite.com/gfx/icons/item_food_biscuit.gif > items/food_biscuit.gif
curl http://data.die2nite.com/gfx/icons/item_food_candies.gif > items/food_candies.gif
curl http://data.die2nite.com/gfx/icons/item_food_chick.gif > items/food_chick.gif
curl http://data.die2nite.com/gfx/icons/item_food_noodles.gif > items/food_noodles.gif
curl http://data.die2nite.com/gfx/icons/item_food_noodles_hot.gif > items/food_noodles_hot.gif
curl http://data.die2nite.com/gfx/icons/item_food_pims.gif > items/food_pims.gif
curl http://data.die2nite.com/gfx/icons/item_food_sandw.gif > items/food_sandw.gif
curl http://data.die2nite.com/gfx/icons/item_food_tarte.gif > items/food_tarte.gif
curl http://data.die2nite.com/gfx/icons/item_fruit.gif > items/fruit.gif
curl http://data.die2nite.com/gfx/icons/item_fruit_part.gif > items/fruit_part.gif
curl http://data.die2nite.com/gfx/icons/item_fruit_sub_part.gif > items/fruit_sub_part.gif
curl http://data.die2nite.com/gfx/icons/item_game_box.gif > items/game_box.gif
curl http://data.die2nite.com/gfx/icons/item_grenade.gif > items/grenade.gif
curl http://data.die2nite.com/gfx/icons/item_grenade_empty.gif > items/grenade_empty.gif
curl http://data.die2nite.com/gfx/icons/item_gun.gif > items/gun.gif
curl http://data.die2nite.com/gfx/icons/item_hmeat.gif > items/hmeat.gif
curl http://data.die2nite.com/gfx/icons/item_home_box.gif > items/home_box.gif
curl http://data.die2nite.com/gfx/icons/item_home_box_xl.gif > items/home_box_xl.gif
curl http://data.die2nite.com/gfx/icons/item_home_def.gif > items/home_def.gif
curl http://data.die2nite.com/gfx/icons/item_iphone.gif > items/iphone.gif
curl http://data.die2nite.com/gfx/icons/item_jerrycan.gif > items/jerrycan.gif
curl http://data.die2nite.com/gfx/icons/item_jerrygun.gif > items/jerrygun.gif
curl http://data.die2nite.com/gfx/icons/item_jerrygun_off.gif > items/jerrygun_off.gif
curl http://data.die2nite.com/gfx/icons/item_jerrygun_part.gif > items/jerrygun_part.gif
curl http://data.die2nite.com/gfx/icons/item_knife.gif > items/knife.gif
curl http://data.die2nite.com/gfx/icons/item_lamp.gif > items/lamp.gif
curl http://data.die2nite.com/gfx/icons/item_lamp_on.gif > items/lamp_on.gif
curl http://data.die2nite.com/gfx/icons/item_lawn.gif > items/lawn.gif
curl http://data.die2nite.com/gfx/icons/item_lawn_part.gif > items/lawn_part.gif
curl http://data.die2nite.com/gfx/icons/item_lights.gif > items/lights.gif
curl http://data.die2nite.com/gfx/icons/item_lock.gif > items/lock.gif
curl http://data.die2nite.com/gfx/icons/item_machine_1.gif > items/machine_1.gif
curl http://data.die2nite.com/gfx/icons/item_machine_2.gif > items/machine_2.gif
curl http://data.die2nite.com/gfx/icons/item_machine_3.gif > items/machine_3.gif
curl http://data.die2nite.com/gfx/icons/item_machine_gun.gif > items/machine_gun.gif
curl http://data.die2nite.com/gfx/icons/item_meat.gif > items/meat.gif
curl http://data.die2nite.com/gfx/icons/item_mecanism.gif > items/mecanism.gif
curl http://data.die2nite.com/gfx/icons/item_meca_parts.gif > items/meca_parts.gif
curl http://data.die2nite.com/gfx/icons/item_metal.gif > items/metal.gif
curl http://data.die2nite.com/gfx/icons/item_metal_bad.gif > items/metal_bad.gif
curl http://data.die2nite.com/gfx/icons/item_metal_beam.gif > items/metal_beam.gif
curl http://data.die2nite.com/gfx/icons/item_mixergun.gif > items/mixergun.gif
curl http://data.die2nite.com/gfx/icons/item_mixergun_empty.gif > items/mixergun_empty.gif
curl http://data.die2nite.com/gfx/icons/item_mixergun_part.gif > items/mixergun_part.gif
curl http://data.die2nite.com/gfx/icons/item_money.gif > items/money.gif
curl http://data.die2nite.com/gfx/icons/item_music.gif > items/music.gif
curl http://data.die2nite.com/gfx/icons/item_music_part.gif > items/music_part.gif
curl http://data.die2nite.com/gfx/icons/item_out_def.gif > items/out_def.gif
curl http://data.die2nite.com/gfx/icons/item_pc.gif > items/pc.gif
curl http://data.die2nite.com/gfx/icons/item_pet_cat.gif > items/pet_cat.gif
curl http://data.die2nite.com/gfx/icons/item_pet_chick.gif > items/pet_chick.gif
curl http://data.die2nite.com/gfx/icons/item_pet_dog.gif > items/pet_dog.gif
curl http://data.die2nite.com/gfx/icons/item_pet_pig.gif > items/pet_pig.gif
curl http://data.die2nite.com/gfx/icons/item_pet_rat.gif > items/pet_rat.gif
curl http://data.die2nite.com/gfx/icons/item_pet_snake.gif > items/pet_snake.gif
curl http://data.die2nite.com/gfx/icons/item_pharma.gif > items/pharma.gif
curl http://data.die2nite.com/gfx/icons/item_pharma_part.gif > items/pharma_part.gif
curl http://data.die2nite.com/gfx/icons/item_pile.gif > items/pile.gif
curl http://data.die2nite.com/gfx/icons/item_pilegun.gif > items/pilegun.gif
curl http://data.die2nite.com/gfx/icons/item_pilegun_empty.gif > items/pilegun_empty.gif
curl http://data.die2nite.com/gfx/icons/item_pilegun_up.gif > items/pilegun_up.gif
curl http://data.die2nite.com/gfx/icons/item_pilegun_upkit.gif > items/pilegun_upkit.gif
curl http://data.die2nite.com/gfx/icons/item_pilegun_up_empty.gif > items/pilegun_up_empty.gif
curl http://data.die2nite.com/gfx/icons/item_pile_broken.gif > items/pile_broken.gif
curl http://data.die2nite.com/gfx/icons/item_plate.gif > items/plate.gif
curl http://data.die2nite.com/gfx/icons/item_plate_raw.gif > items/plate_raw.gif
curl http://data.die2nite.com/gfx/icons/item_pocket_belt.gif > items/pocket_belt.gif
curl http://data.die2nite.com/gfx/icons/item_poison.gif > items/poison.gif
curl http://data.die2nite.com/gfx/icons/item_poison_part.gif > items/poison_part.gif
curl http://data.die2nite.com/gfx/icons/item_postal_box.gif > items/postal_box.gif
curl http://data.die2nite.com/gfx/icons/item_postal_box_xl.gif > items/postal_box_xl.gif
curl http://data.die2nite.com/gfx/icons/item_powder.gif > items/powder.gif
curl http://data.die2nite.com/gfx/icons/item_radio_off.gif > items/radio_off.gif
curl http://data.die2nite.com/gfx/icons/item_radio_on.gif > items/radio_on.gif
curl http://data.die2nite.com/gfx/icons/item_radius_mk2.gif > items/radius_mk2.gif
curl http://data.die2nite.com/gfx/icons/item_radius_mk2_part.gif > items/radius_mk2_part.gif
curl http://data.die2nite.com/gfx/icons/item_repair_kit.gif > items/repair_kit.gif
curl http://data.die2nite.com/gfx/icons/item_repair_kit_part.gif > items/repair_kit_part.gif
curl http://data.die2nite.com/gfx/icons/item_repair_kit_part_raw.gif > items/repair_kit_part_raw.gif
curl http://data.die2nite.com/gfx/icons/item_repair_one.gif > items/repair_one.gif
curl http://data.die2nite.com/gfx/icons/item_rhum.gif > items/rhum.gif
curl http://data.die2nite.com/gfx/icons/item_rp_book.gif > items/rp_book.gif
curl http://data.die2nite.com/gfx/icons/item_rp_book2.gif > items/rp_book2.gif
curl http://data.die2nite.com/gfx/icons/item_rp_letter.gif > items/rp_letter.gif
curl http://data.die2nite.com/gfx/icons/item_rp_manual.gif > items/rp_manual.gif
curl http://data.die2nite.com/gfx/icons/item_rp_scroll.gif > items/rp_scroll.gif
curl http://data.die2nite.com/gfx/icons/item_rp_twin.gif > items/rp_twin.gif
curl http://data.die2nite.com/gfx/icons/item_rsc_pack_1.gif > items/rsc_pack_1.gif
curl http://data.die2nite.com/gfx/icons/item_rsc_pack_2.gif > items/rsc_pack_2.gif
curl http://data.die2nite.com/gfx/icons/item_rsc_pack_3.gif > items/rsc_pack_3.gif
curl http://data.die2nite.com/gfx/icons/item_rustine.gif > items/rustine.gif
curl http://data.die2nite.com/gfx/icons/item_safe.gif > items/safe.gif
curl http://data.die2nite.com/gfx/icons/item_saw_tool.gif > items/saw_tool.gif
curl http://data.die2nite.com/gfx/icons/item_saw_tool_part.gif > items/saw_tool_part.gif
curl http://data.die2nite.com/gfx/icons/item_screw.gif > items/screw.gif
curl http://data.die2nite.com/gfx/icons/item_sheet.gif > items/sheet.gif
curl http://data.die2nite.com/gfx/icons/item_small_knife.gif > items/small_knife.gif
curl http://data.die2nite.com/gfx/icons/item_smelly_meat.gif > items/smelly_meat.gif
curl http://data.die2nite.com/gfx/icons/item_smoke_bomb.gif > items/smoke_bomb.gif
curl http://data.die2nite.com/gfx/icons/item_spices.gif > items/spices.gif
curl http://data.die2nite.com/gfx/icons/item_sport_elec.gif > items/sport_elec.gif
curl http://data.die2nite.com/gfx/icons/item_sport_elec_empty.gif > items/sport_elec_empty.gif
curl http://data.die2nite.com/gfx/icons/item_staff.gif > items/staff.gif
curl http://data.die2nite.com/gfx/icons/item_swiss_knife.gif > items/swiss_knife.gif
curl http://data.die2nite.com/gfx/icons/item_table.gif > items/table.gif
curl http://data.die2nite.com/gfx/icons/item_tagger.gif > items/tagger.gif
curl http://data.die2nite.com/gfx/icons/item_taser.gif > items/taser.gif
curl http://data.die2nite.com/gfx/icons/item_taser_empty.gif > items/taser_empty.gif
curl http://data.die2nite.com/gfx/icons/item_torch.gif > items/torch.gif
curl http://data.die2nite.com/gfx/icons/item_torch_off.gif > items/torch_off.gif
curl http://data.die2nite.com/gfx/icons/item_trestle.gif > items/trestle.gif
curl http://data.die2nite.com/gfx/icons/item_tube.gif > items/tube.gif
curl http://data.die2nite.com/gfx/icons/item_undef.gif > items/undef.gif
curl http://data.die2nite.com/gfx/icons/item_vegetable.gif > items/vegetable.gif
curl http://data.die2nite.com/gfx/icons/item_vegetable_tasty.gif > items/vegetable_tasty.gif
curl http://data.die2nite.com/gfx/icons/item_vibr.gif > items/vibr.gif
curl http://data.die2nite.com/gfx/icons/item_vibr_empty.gif > items/vibr_empty.gif
curl http://data.die2nite.com/gfx/icons/item_vodka.gif > items/vodka.gif
curl http://data.die2nite.com/gfx/icons/item_water.gif > items/water.gif
curl http://data.die2nite.com/gfx/icons/item_watergun_1.gif > items/watergun_1.gif
curl http://data.die2nite.com/gfx/icons/item_watergun_2.gif > items/watergun_2.gif
curl http://data.die2nite.com/gfx/icons/item_watergun_3.gif > items/watergun_3.gif
curl http://data.die2nite.com/gfx/icons/item_watergun_empty.gif > items/watergun_empty.gif
curl http://data.die2nite.com/gfx/icons/item_watergun_opt_1.gif > items/watergun_opt_1.gif
curl http://data.die2nite.com/gfx/icons/item_watergun_opt_2.gif > items/watergun_opt_2.gif
curl http://data.die2nite.com/gfx/icons/item_watergun_opt_3.gif > items/watergun_opt_3.gif
curl http://data.die2nite.com/gfx/icons/item_watergun_opt_4.gif > items/watergun_opt_4.gif
curl http://data.die2nite.com/gfx/icons/item_watergun_opt_5.gif > items/watergun_opt_5.gif
curl http://data.die2nite.com/gfx/icons/item_watergun_opt_empty.gif > items/watergun_opt_empty.gif
curl http://data.die2nite.com/gfx/icons/item_watergun_opt_part.gif > items/watergun_opt_part.gif
curl http://data.die2nite.com/gfx/icons/item_water_can_1.gif > items/water_can_1.gif
curl http://data.die2nite.com/gfx/icons/item_water_can_2.gif > items/water_can_2.gif
curl http://data.die2nite.com/gfx/icons/item_water_can_3.gif > items/water_can_3.gif
curl http://data.die2nite.com/gfx/icons/item_water_can_empty.gif > items/water_can_empty.gif
curl http://data.die2nite.com/gfx/icons/item_water_cleaner.gif > items/water_cleaner.gif
curl http://data.die2nite.com/gfx/icons/item_water_cup.gif > items/water_cup.gif
curl http://data.die2nite.com/gfx/icons/item_water_cup_part.gif > items/water_cup_part.gif
curl http://data.die2nite.com/gfx/icons/item_wood2.gif > items/wood2.gif
curl http://data.die2nite.com/gfx/icons/item_woodsteak.gif > items/woodsteak.gif
curl http://data.die2nite.com/gfx/icons/item_wood_bad.gif > items/wood_bad.gif
curl http://data.die2nite.com/gfx/icons/item_wood_beam.gif > items/wood_beam.gif
curl http://data.die2nite.com/gfx/icons/item_wood_log.gif > items/wood_log.gif
curl http://data.die2nite.com/gfx/icons/item_wood_plate.gif > items/wood_plate.gif
curl http://data.die2nite.com/gfx/icons/item_wood_plate_part.gif > items/wood_plate_part.gif
curl http://data.die2nite.com/gfx/icons/item_wrench.gif > items/wrench.gif
curl http://data.die2nite.com/gfx/icons/item_xanax.gif > items/xanax.gif
curl http://data.die2nite.com/gfx/icons/item_teddy.gif > items/teddy.gif 
curl http://data.die2nite.com/gfx/icons/item_rp_sheets.gif > items/rp_sheets.gif 
curl http://data.die2nite.com/gfx/icons/item_fruit.gif > items/fruit.gif 
curl http://data.die2nite.com/gfx/icons/item_apple.gif > items/apple.gif 
