update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Abandoned_Construction_Site" where name="Abandoned Construction Site";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Abandoned_Park" where name="Abandoned Park";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Abandoned_Supermarket" where name="Abandoned Supermarket";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Abandoned_Well" where name="Abandonned Well";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Army_Outpost" where name="Army Outpost";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Ambulance" where name="Ambulance";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Blocked_Road" where name="Blocked Road";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Broken-down_Tank" where name="Broken-down Tank";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Burnt_School" where name="Burnt School";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Cave" where name="Cave";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Citizen.27s_Home" where name="Citizen's Home";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Citizen.27s_Tent" where name="Citizen's Tent";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Collapsed_Mineshaft" where name="Collapsed Mineshaft";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Collapsed_Quarry" where name="Collapsed Quarry";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Construction_Site_Shelter" where name="Construction Site Shelter";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Cosmetics_Lab" where name="Cosmetics Lab";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Dark_Woods" where name="Dark Woods";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Derelict_Villa" where name="Derelict Villa";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Deserted_Freight_Yard" where name="Deserted Freight Yard";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Destroyed_Pharmacy" where name="Destroyed Pharmacy";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Dilapidated_Building" where name="Dilapidated Building";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Disused_Car_Park" where name="Disused Car Park";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Disused_Silos" where name="Disused Silos";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Disused_Warehouse" where name="Disused Warehouse";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Duke.27s_Villa" where name="Duke's Villa";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Equipped_Trench" where name="Equipped Trench";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Fairground_Stall" where name="Fairground Stall";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Family_Tomb" where name="Family Tomb";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Fast_Food_Restaurant" where name="Fast Food Restaurant";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Fraser_D.27s_Kebab-ish" where name="Fraser D's Kebab-ish";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Garden_Shed" where name="Garden Shed";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Guns_.27n.27_Zombies_Armoury" where name="Guns 'n' Zombies Armoury";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Home_Depot" where name="Home Depot";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Indian_Burial_Ground" where name="Indian Burial Ground";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Looted_Supermarket" where name="Looted Supermarket";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Mac.27s_Atomic_Cafe" where name="Mac's Atomic Cafe";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#The_.27Mayor_Mobile.27" where name=" The 'Mayor-Mobile'";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Mini-Market" where name="Mini-Market";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Motel_666.EF.BF.BD_Dusk" where id=51;
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Motorway_Services" where name="Motorway Services";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Nuclear_Bunker" where name="Nuclear Bunker";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Old_Aerodome" where id=48;
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Old_Bicycle_Hire_Shop" where name="Old Bicycle Hire Shop";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Old_Field_Hospital" where name="Old Field Hospital";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Old_Hydraulic_Pump" where name="Old Hydraulic Pump";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Old_Police_Station" where name="Old Police Station";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Old_Water_Processing_Plant" where name="Old Water Processing Plant";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Once-Inhabited_Cave" where name="Once-Inhabited Cave";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#PI-KEYA_Furniture" where name="PI-KEYA Furniture";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Plane_Crash_Site" where name="Plane Crash Site";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Post_Office" where name="Post Office";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Scottish_Smith.27s_Superstore" where name="Scottish Smith's Superstore";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Shady_Bar" where name="Shady Bar";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Small_House" where name="Small House";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Smugglers.27_Cache" where name="Smugglers' Cache";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Town_Library" where name="Town Library";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Warehouse" where name="Warehouse";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Water_Processing_Plant" where name="Water Processing Plant";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Wrecked_Cars" where name="Wrecked Cars";
update unique_outside_buildings set url="http://die2nitewiki.com/wiki/Ruins#Wrecked_Transporter" where name="Wrecked Transporter";
update unique_outside_buildings set url='http://die2nitewiki.com/wiki/Abandoned_Bunker' where id=100;
update unique_outside_buildings set url='http://die2nitewiki.com/wiki/Abandoned_Hotel' where id=101;
update unique_outside_buildings set url='http://die2nitewiki.com/wiki/Abandoned_Hospital' where id=102;
