insert into unique_items (id, image, name, category) values (2,'pile','Battery','RESOURCES');
insert into unique_items (id, image, name, category) values (40,'courroie','Belt','RESOURCES');
insert into unique_items (id, image, name, category) values (165,'electro_box','Broken Electronic Device','RESOURCES');
insert into unique_items (id, image, name, category) values (132,'deto','Compact Detonator','RESOURCES');
insert into unique_items (id, image, name, category) values (84,'tube','Copper Pipe','RESOURCES');
insert into unique_items (id, image, name, category) values (81,'rustine','Duct Tape','RESOURCES');
insert into unique_items (id, image, name, category) values (101,'electro','Electronic component','RESOURCES');
insert into unique_items (id, image, name, category) values (41,'meca_parts','Handful of nuts and bolts','RESOURCES');
insert into unique_items (id, image, name, category) values (168,'mecanism','Mechanism','RESOURCES');
insert into unique_items (id, image, name, category) values (160,'metal_beam','Metal Support','RESOURCES');
insert into unique_items (id, image, name, category) values (159,'wood_beam','Patchwork Beam','RESOURCES');
insert into unique_items (id, image, name, category) values (162,'wood_bad','Rotting Log','RESOURCES');
insert into unique_items (id, image, name, category) values (161,'metal_bad','Scrap Metal','RESOURCES');
insert into unique_items (id, image, name, category) values (73,'explo','Semtex','RESOURCES');
insert into unique_items (id, image, name, category) values (59,'wood2','Twisted Plank','RESOURCES');
insert into unique_items (id, image, name, category) values (60,'metal','Wrought Iron','RESOURCES');
insert into unique_items (id, image, name, category) values (13,'wrench','Adjustable Spanner','ARMOURY');
insert into unique_items (id, image, name, category) values (114,'watergun_opt_1','Aqua-Splash (1 shot)','ARMOURY');
insert into unique_items (id, image, name, category) values (113,'watergun_opt_2','Aqua-Splash (2 shots)','ARMOURY');
insert into unique_items (id, image, name, category) values (112,'watergun_opt_3','Aqua-Splash (3 shots)','ARMOURY');
insert into unique_items (id, image, name, category) values (208,'watergun_opt_5','Aqua-Splash (5 shots)','ARMOURY');
insert into unique_items (id, image, name, category) values (8,'watergun_opt_empty','Aqua-Splash (empty)','ARMOURY');
insert into unique_items (id, image, name, category) values (117,'pilegun_empty','Battery Launcher 1-ITF (empty)','ARMOURY');
insert into unique_items (id, image, name, category) values (5,'pilegun','Battery Launcher 1-ITF (loaded)','ARMOURY');
insert into unique_items (id, image, name, category) values (212,'pilegun_up_empty','Battery Launcher Mk. II (empty)','ARMOURY');
insert into unique_items (id, image, name, category) values (213,'pilegun_up','Battery Launcher Mk. II (loaded)','ARMOURY');
insert into unique_items (id, image, name, category) values (20,'cutter','Box Cutter','ARMOURY');
insert into unique_items (id, image, name, category) values (158,'bone','Broken Human Bone','ARMOURY');
insert into unique_items (id, image, name, category) values (234,'torch_off','Burnt out Torch','ARMOURY');
insert into unique_items (id, image, name, category) values (23,'can_opener','Can Opener','ARMOURY');
insert into unique_items (id, image, name, category) values (116,'chainsaw_empty','Chainsaw (incomplete)','ARMOURY');
insert into unique_items (id, image, name, category) values (10,'chainsaw','Chainsaw (loaded)','ARMOURY');
insert into unique_items (id, image, name, category) values (122,'big_pgun_empty','Devastator (empty)','ARMOURY');
insert into unique_items (id, image, name, category) values (123,'big_pgun','Devastator (loaded)','ARMOURY');
insert into unique_items (id, image, name, category) values (9,'mixergun','Electric Whisk (charged)','ARMOURY');
insert into unique_items (id, image, name, category) values (115,'mixergun_empty','Electric Whisk (incomplete)','ARMOURY');
insert into unique_items (id, image, name, category) values (313,'boomfruit','Exploding Grapefruit','ARMOURY');
insert into unique_items (id, image, name, category) values (77,'bgrenade','Exploding Water Bomb','ARMOURY');
insert into unique_items (id, image, name, category) values (127,'jerrygun','Jerrycan Gun (ready)','ARMOURY');
insert into unique_items (id, image, name, category) values (70,'jerrygun_off','Jerrycan Pump (empty)','ARMOURY');
insert into unique_items (id, image, name, category) values (11,'lawn','Lawnmower','ARMOURY');
insert into unique_items (id, image, name, category) values (17,'cutcut','Machete','ARMOURY');
insert into unique_items (id, image, name, category) values (286,'iphone','Mobile Phone','ARMOURY');
insert into unique_items (id, image, name, category) values (18,'small_knife','Pathetic Penknife','ARMOURY');
insert into unique_items (id, image, name, category) values (76,'grenade_empty','Plastic Bag','ARMOURY');
insert into unique_items (id, image, name, category) values (78,'bgrenade_empty','Plastic Bag and Semtex','ARMOURY');
insert into unique_items (id, image, name, category) values (196,'chain','Rusty Chain','ARMOURY');
insert into unique_items (id, image, name, category) values (14,'screw','Screwdriver','ARMOURY');
insert into unique_items (id, image, name, category) values (16,'knife','Serrated Knife','ARMOURY');
insert into unique_items (id, image, name, category) values (15,'staff','Staff','ARMOURY');
insert into unique_items (id, image, name, category) values (19,'swiss_knife','Swiss Army Knife','ARMOURY');
insert into unique_items (id, image, name, category) values (7,'taser','Taser','ARMOURY');
insert into unique_items (id, image, name, category) values (118,'taser_empty','Taser (incomplete)','ARMOURY');
insert into unique_items (id, image, name, category) values (62,'grenade','Water Bomb','ARMOURY');
insert into unique_items (id, image, name, category) values (207,'watergun_1','Water Pistol (1 shot)','ARMOURY');
insert into unique_items (id, image, name, category) values (206,'watergun_2','Water Pistol (2 shots)','ARMOURY');
insert into unique_items (id, image, name, category) values (205,'watergun_3','Water Pistol (3 shots)','ARMOURY');
insert into unique_items (id, image, name, category) values (111,'watergun_empty','Water Pistol (empty)','ARMOURY');
insert into unique_items (id, image, name, category) values (309,'bplan_box','Architect\'s Chest','CONTAINERS_AND_BOXES');
insert into unique_items (id, image, name, category) values (152,'game_box','Box of Games','CONTAINERS_AND_BOXES');
insert into unique_items (id, image, name, category) values (90,'chest','Chest','CONTAINERS_AND_BOXES');
insert into unique_items (id, image, name, category) values (102,'chest_citizen','Citizen\'s Welcome Pack','CONTAINERS_AND_BOXES');
insert into unique_items (id, image, name, category) values (217,'rsc_pack_1','Construction Kit','CONTAINERS_AND_BOXES');
insert into unique_items (id, image, name, category) values (216,'rsc_pack_2','Construction Kit','CONTAINERS_AND_BOXES');
insert into unique_items (id, image, name, category) values (215,'rsc_pack_3','Construction Kit','CONTAINERS_AND_BOXES');
insert into unique_items (id, image, name, category) values (202,'book_gen_letter','Envelope','CONTAINERS_AND_BOXES');
insert into unique_items (id, image, name, category) values (227,'postal_box','Gift Parcel','CONTAINERS_AND_BOXES');
insert into unique_items (id, image, name, category) values (91,'chest_xl','Large Chest','CONTAINERS_AND_BOXES');
insert into unique_items (id, image, name, category) values (229,'food_armag','Lunch Box','CONTAINERS_AND_BOXES');
insert into unique_items (id, image, name, category) values (25,'bag','Manbag','CONTAINERS_AND_BOXES');
insert into unique_items (id, image, name, category) values (203,'book_gen_box','Parcel','CONTAINERS_AND_BOXES');
insert into unique_items (id, image, name, category) values (243,'safe','Safe','CONTAINERS_AND_BOXES');
insert into unique_items (id, image, name, category) values (310,'bplan_box_e','Sealed Architect\'s Chest','CONTAINERS_AND_BOXES');
insert into unique_items (id, image, name, category) values (22,'cart','Shopping Trolley','CONTAINERS_AND_BOXES');
insert into unique_items (id, image, name, category) values (92,'chest_tools','Toolbox','CONTAINERS_AND_BOXES');
insert into unique_items (id, image, name, category) values (88,'pocket_belt','Utility belt','CONTAINERS_AND_BOXES');
insert into unique_items (id, image, name, category) values (218,'car_door','Car Door','DEFENSES');
insert into unique_items (id, image, name, category) values (45,'pet_dog','Guard Dog','DEFENSES');
insert into unique_items (id, image, name, category) values (170,'table','Järpen Table','DEFENSES');
insert into unique_items (id, image, name, category) values (31,'bed','Mattress','DEFENSES');
insert into unique_items (id, image, name, category) values (107,'door','Old Door','DEFENSES');
insert into unique_items (id, image, name, category) values (64,'plate','Sheet Metal','DEFENSES');
insert into unique_items (id, image, name, category) values (179,'wood_plate','Solid Wooden Board','DEFENSES');
insert into unique_items (id, image, name, category) values (233,'torch','Torch','DEFENSES');
insert into unique_items (id, image, name, category) values (169,'trestle','Trestle','DEFENSES');
insert into unique_items (id, image, name, category) values (134,'concrete_wall','Unshaped Concrete Blocks','DEFENSES');
insert into unique_items (id, image, name, category) values (98,'coffee','Bloody hot coffee','FOOD');
insert into unique_items (id, image, name, category) values (236,'chama_tasty','Burnt Marshmallows','FOOD');
insert into unique_items (id, image, name, category) values (3,'can','Can','FOOD');
insert into unique_items (id, image, name, category) values (148,'food_noodles','Chinese Noodles','FOOD');
insert into unique_items (id, image, name, category) values (197,'dish','Dodgy Homemade Dish','FOOD');
insert into unique_items (id, image, name, category) values (139,'food_bag','Doggy Bag','FOOD');
insert into unique_items (id, image, name, category) values (142,'food_bar3','Dried Chewing Gum','FOOD');
insert into unique_items (id, image, name, category) values (235,'chama','Dried Marshmallows','FOOD');
insert into unique_items (id, image, name, category) values (311,'egg','Egg','FOOD');
insert into unique_items (id, image, name, category) values (260,'fruit','Fleshroom Puree','FOOD');
insert into unique_items (id, image, name, category) values (138,'chest_food','Food Parcel','FOOD');
insert into unique_items (id, image, name, category) values (144,'food_chick','Half-eaten Chicken Wings','FOOD');
insert into unique_items (id, image, name, category) values (230,'food_candies','Handful of Sweets','FOOD');
insert into unique_items (id, image, name, category) values (74,'hmeat','Human Flesh','FOOD');
insert into unique_items (id, image, name, category) values (172,'vegetable_tasty','Intestine Melon','FOOD');
insert into unique_items (id, image, name, category) values (157,'bone_meat','Meaty Bone','FOOD');
insert into unique_items (id, image, name, category) values (147,'food_sandw','Mouldy Ham Sandwich','FOOD');
insert into unique_items (id, image, name, category) values (141,'food_bar2','Mouldy Neapolitan','FOOD');
insert into unique_items (id, image, name, category) values (224,'can_open','Open Can','FOOD');
insert into unique_items (id, image, name, category) values (4,'can_open','Open Can','FOOD');
insert into unique_items (id, image, name, category) values (145,'food_pims','Out-of-Date Biscuits','FOOD');
insert into unique_items (id, image, name, category) values (140,'food_bar1','Packet of Soft Crisps','FOOD');
insert into unique_items (id, image, name, category) values (264,'water_cup','Purified Stagnant Water','FOOD');
insert into unique_items (id, image, name, category) values (143,'food_biscuit','Rancid Jaffa Cakes','FOOD');
insert into unique_items (id, image, name, category) values (281,'woodsteak','SawdustSteak','FOOD');
insert into unique_items (id, image, name, category) values (150,'food_noodles_hot','Spicy Chinese Noodles','FOOD');
insert into unique_items (id, image, name, category) values (146,'food_tarte','Stale Tart','FOOD');
insert into unique_items (id, image, name, category) values (108,'vegetable','Suspicious-looking Vegetable','FOOD');
insert into unique_items (id, image, name, category) values (198,'dish_tasty','Tasty Homemade Dish','FOOD');
insert into unique_items (id, image, name, category) values (52,'meat','Tasty-looking Steak','FOOD');
insert into unique_items (id, image, name, category) values (53,'undef','Unspecified Meat','FOOD');
insert into unique_items (id, image, name, category) values (69,'vodka','Vodka Marinostov','FOOD');
insert into unique_items (id, image, name, category) values (97,'rhum','\'Wake The Dead\'','FOOD');
insert into unique_items (id, image, name, category) values (246,'water_can_1','Water Cooler Bottle (1 ration)','FOOD');
insert into unique_items (id, image, name, category) values (247,'water_can_2','Water Cooler Bottle (2 rations)','FOOD');
insert into unique_items (id, image, name, category) values (248,'water_can_3','Water Cooler Bottle (3 rations)','FOOD');
insert into unique_items (id, image, name, category) values (1,'water','Water Ration','FOOD');
insert into unique_items (id, image, name, category) values (222,'water','Water Ration','FOOD');
insert into unique_items (id, image, name, category) values (32,'lamp','Bedside Lamp (off)','FURNITURE');
insert into unique_items (id, image, name, category) values (93,'lamp_on','Bedside Lamp (on)','FURNITURE');
insert into unique_items (id, image, name, category) values (188,'machine_3','Beer Fridge','FURNITURE');
insert into unique_items (id, image, name, category) values (200,'home_box','Boxes','FURNITURE');
insert into unique_items (id, image, name, category) values (99,'coffee_machine','Cafetière','FURNITURE');
insert into unique_items (id, image, name, category) values (187,'machine_2','Carcinogenic Oven','FURNITURE');
insert into unique_items (id, image, name, category) values (36,'door_carpet','Doormat','FURNITURE');
insert into unique_items (id, image, name, category) values (128,'chair_basic','Ektorp-Gluten Chair','FURNITURE');
insert into unique_items (id, image, name, category) values (46,'pet_cat','Fat Cat','FURNITURE');
insert into unique_items (id, image, name, category) values (199,'home_box_xl','Iron Chest','FURNITURE');
insert into unique_items (id, image, name, category) values (130,'machine_gun','Machine Gun (empty)','FURNITURE');
insert into unique_items (id, image, name, category) values (201,'home_def','Makeshift Barricade','FURNITURE');
insert into unique_items (id, image, name, category) values (34,'music_part','Mini HI-Fi (Broken)','FURNITURE');
insert into unique_items (id, image, name, category) values (94,'music','Mini HiFi (on)','FURNITURE');
insert into unique_items (id, image, name, category) values (186,'machine_1','Old Washing Machine','FURNITURE');
insert into unique_items (id, image, name, category) values (35,'lock','Padlock and Chain','FURNITURE');
insert into unique_items (id, image, name, category) values (242,'pc','PC Base Unit','FURNITURE');
insert into unique_items (id, image, name, category) values (33,'carpet','Persian Rug','FURNITURE');
insert into unique_items (id, image, name, category) values (164,'wood_log','Quality Log','FURNITURE');
insert into unique_items (id, image, name, category) values (105,'radio_on','Radio Cassette Player ','FURNITURE');
insert into unique_items (id, image, name, category) values (129,'gun','Revolver (empty)','FURNITURE');
insert into unique_items (id, image, name, category) values (29,'chair','Rocking Chair','FURNITURE');
insert into unique_items (id, image, name, category) values (180,'money','Wad of Cash','FURNITURE');
insert into unique_items (id, image, name, category) values (204,'fence','Wire Mesh','FURNITURE');
insert into unique_items (id, image, name, category) values (51,'drug','Anabolic Steroids','PHARMACY');
insert into unique_items (id, image, name, category) values (223,'drug','Anabolic Steroids','PHARMACY');
insert into unique_items (id, image, name, category) values (66,'bandage','Bandage','PHARMACY');
insert into unique_items (id, image, name, category) values (250,'beta_drug_bad','Betapropine 5mg (expired)','PHARMACY');
insert into unique_items (id, image, name, category) values (106,'cyanure','Cyanide','PHARMACY');
insert into unique_items (id, image, name, category) values (103,'drug_water','Hydratone 100mg','PHARMACY');
insert into unique_items (id, image, name, category) values (136,'disinfect','Paracetoid 7g','PHARMACY');
insert into unique_items (id, image, name, category) values (95,'pharma','Pharmaceutical Products','PHARMACY');
insert into unique_items (id, image, name, category) values (259,'pharma_part','Thick Solution','PHARMACY');
insert into unique_items (id, image, name, category) values (89,'drug_hero','Twinoid 500mg','PHARMACY');
insert into unique_items (id, image, name, category) values (135,'drug_random','Unlabelled Drug','PHARMACY');
insert into unique_items (id, image, name, category) values (28,'xanax','Valium Shot','PHARMACY');
insert into unique_items (id, image, name, category) values (171,'water_cleaner','Water Purifying Tablets','PHARMACY');
insert into unique_items (id, image, name, category) values (153,'watergun_opt_part','Aqua-Splash (incomplete)','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (133,'concrete','Bag of Cement','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (48,'vibr','Big Rubber D*** (charged)','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (154,'vibr_empty','Big Rubber D*** (incomplete)','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (26,'lights','Box of Matches','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (167,'saw_tool_part','Broken Hacksaw','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (219,'car_door_part','Car Door (incomplete)','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (42,'pet_chick','Chicken','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (305,'bplan_c','Construction Blueprint (common)','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (307,'bplan_r','Construction Blueprint (rare)','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (306,'bplan_u','Construction Blueprint (uncommon)','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (221,'poison_part','Corrosive Liquid','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (178,'wood_plate_part','Crate Lid','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (214,'pile_broken','Crushed Battery','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (124,'big_pgun_part','Devastator (incomplete)','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (38,'dice','Dice','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (82,'lawn_part','Dismantled Mower','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (120,'sport_elec','EMS System (charged)','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (119,'sport_elec_empty','EMS System (incomplete)','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (39,'engine','Engine','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (185,'engine_part','Engine (incomplete)','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (287,'smelly_meat','Festering Flesh','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (174,'flash','Flash Grenade','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (173,'powder','Flash Powder','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (166,'deco_box','Flatpacked Furniture','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (252,'fruit_sub_part','Fleshrooms','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (58,'jerrycan','Full Jerrycan','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (44,'pet_rat','Giant Rat','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (258,'flesh','Grisly Bomb','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (54,'sheet','Groundsheet','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (163,'saw_tool','Hacksaw','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (47,'pet_snake','Huge Snake (Ophiophagus trouser)','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (100,'coffee_machine_part','Incomplete Cafetière','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (79,'chainsaw_part','Incomplete Chainsaw','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (151,'cards','Incomplete Deck of Cards','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (80,'mixergun_part','Incomplete Whisk','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (191,'rp_manual','Instruction Manual','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (65,'jerrygun_part','Jerrycan Pump (unattached)','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (184,'repair_one','Kwik-Fix','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (192,'rp_scroll','Label','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (137,'digger','Ness-Quick Weedkiller','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (210,'cigs','Opened packet of Cigarettes','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (299,'smoke_bomb','« Pine Fresh » Smoke Bomb','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (257,'flesh_part','Pound of Flesh','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (211,'pilegun_upkit','PUTA Mark II Calibrator','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (104,'radio_off','Radio Cassette Player (no battery)','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (183,'radius_mk2','Radius Mark II','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (182,'radius_mk2_part','Radius Mark II (incomplete)','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (125,'tagger','Radius Radar Beacon','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (110,'repair_kit','Repair Kit','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (109,'repair_kit_part','Repair Kit (damaged)','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (96,'plate_raw','Sheet Metal (parts)','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (231,'out_def','Sheet of Plywood','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (263,'water_cup_part','Stagnant Water Can','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (253,'fruit_part','Sticky Pastry Ball','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (43,'pet_pig','Stinking Pig','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (149,'spices','Strong Spices','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (181,'repair_kit_part_raw','Tool Bag','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (220,'poison','Vial of Poison','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (245,'water_can_empty','Water Cooler Bottle (empty)','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (85,'cart_part','Wonky Shopping Trolley','MISCELLANEOUS');
insert into unique_items (id, image, name, category) values (314,'bplan_drop','Worn Leather Bag','MISCELLANEOUS');
